"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 15:57:28.125578
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


AUDIT_GUARD = """
CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('season', sa.String(length=30), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expeditions')),
    sa.UniqueConstraint('code', name=op.f('uq_expeditions_code'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_sources_key'))
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations')),
    sa.UniqueConstraint('name', name=op.f('uq_stations_name'))
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('key', name=op.f('uq_topics_key'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('curator', 'reviewer', 'admin')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=True),
    sa.Column('translation_of_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('answer', 'lesson', 'announcement', 'social_post')", name=op.f('ck_drafts_kind')),
    sa.CheckConstraint("language IN ('en', 'hi')", name=op.f('ck_drafts_language')),
    sa.CheckConstraint("status IN ('ai_draft', 'auto_checked', 'approved', 'rejected', 'published')", name=op.f('ck_drafts_status')),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], name=op.f('fk_drafts_expedition_id_expeditions')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['drafts.id'], name=op.f('fk_drafts_supersedes_id_drafts')),
    sa.ForeignKeyConstraint(['translation_of_id'], ['drafts.id'], name=op.f('fk_drafts_translation_of_id_drafts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts'))
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_path', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('harvested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("item_type IN ('report', 'paper', 'news', 'video', 'photo', 'dataset_link')", name=op.f('ck_items_item_type')),
    sa.ForeignKeyConstraint(['parent_id'], ['items.id'], name=op.f('fk_items_parent_id_items')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_items_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_items_source_id'))
    )
    op.create_index(op.f('ix_items_parent_id'), 'items', ['parent_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(section_title, '') || ' ' || text)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('text_origin', sa.String(length=20), nullable=False),
    sa.CheckConstraint("text_origin IN ('text_layer', 'ocr', 'mixed')", name=op.f('ck_chunks_text_origin')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_chunks_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('item_id', 'seq', name=op.f('uq_chunks_item_id'))
    )
    op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('draft_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('cited_chunk_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('check_result', sa.String(length=20), nullable=True),
    sa.Column('check_reason', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("check_result IS NULL OR check_result IN ('supported', 'partial', 'unsupported')", name=op.f('ck_draft_sentences_check_result')),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_sentences_draft_id_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_sentences')),
    sa.UniqueConstraint('draft_id', 'seq', name=op.f('uq_draft_sentences_draft_id'))
    )
    op.create_table('eval_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answerable', sa.Boolean(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('expected_item_id', sa.Integer(), nullable=True),
    sa.Column('expected_page', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expected_item_id'], ['items.id'], name=op.f('fk_eval_questions_expected_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_questions'))
    )
    op.create_table('item_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(link_type = 'expedition') = (expedition_id IS NOT NULL) AND (link_type = 'station') = (station_id IS NOT NULL) AND (link_type = 'topic') = (topic_id IS NOT NULL) AND (link_type = 'year') = (year IS NOT NULL)", name=op.f('ck_item_links_one_target')),
    sa.CheckConstraint("link_type IN ('expedition', 'station', 'topic', 'year')", name=op.f('ck_item_links_link_type')),
    sa.CheckConstraint("method IN ('rule', 'model', 'manual')", name=op.f('ck_item_links_method')),
    sa.CheckConstraint("status IN ('confirmed', 'unconfirmed', 'rejected')", name=op.f('ck_item_links_status')),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], name=op.f('fk_item_links_expedition_id_expeditions')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_links_item_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_item_links_station_id_stations')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_item_links_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_links')),
    sa.UniqueConstraint('item_id', 'link_type', 'expedition_id', 'station_id', 'topic_id', 'year', name='uq_item_links_target', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_item_links_item_id'), 'item_links', ['item_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('printed_page', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_origin', sa.String(length=20), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.CheckConstraint("text_origin IN ('text_layer', 'ocr', 'mixed')", name=op.f('ck_pages_text_origin')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_pages_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('item_id', 'page_no', name=op.f('uq_pages_item_id'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approve', 'reject', 'edit', 'publish')", name=op.f('ck_reviews_decision')),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_reviews_draft_id_drafts')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###

    # Hand-written: the audit log can only grow. UPDATE, DELETE and TRUNCATE raise an error.
    op.execute(AUDIT_GUARD)
    op.execute(
        "CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()"
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('pages')
    op.drop_index(op.f('ix_item_links_item_id'), table_name='item_links')
    op.drop_table('item_links')
    op.drop_table('eval_questions')
    op.drop_table('draft_sentences')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunks')
    op.drop_index(op.f('ix_items_parent_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('drafts')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('stations')
    op.drop_table('sources')
    op.drop_table('expeditions')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
